### ISSUE TITLE
handle nested array type 

### ISSUE THREAD

**Issue by matthargett** [Kampfkarren/full-moon#188]
From Discord:

just tested this now, it seems to be a different bug actually.
The issue seems to be the `Parameters` property, looks like we don't handle an array type containing another array/table inside of it
```lua
export type Foo = { { string } }
export type Foo = { {Name: string, Foo: number} }
```
both fail

https://github.com/Kampfkarren/full-moon/blob/main/full-moon/src/ast/parsers.rs#L1519-L1521 seems to be the culrprit,
for some reason this passes - it looks like it reaches the second `{`, stops, and successfully parses as zero fields, which is incorrect.

**Comment by JohnnyMorganz** [comment]
The issue here is that `ZeroOrMoreDelimited` looks to attempt to parse using `ParseTypeField`, which originally starts with `ParseTypeFieldKey`. ParseTypeFieldKey looks for a `[` or an identifier, but otherwise returns `Err(InternalAstError::NoMatch)`.

This is an issue, since `ZeroOrMoreDelimited` uses `keep_going!`, defined as:
https://github.com/Kampfkarren/full-moon/blob/633774a2d8d9b0fee7156f5db544dc246f70d60c/full-moon/src/ast/parser_util.rs#L169-L177

https://github.com/Kampfkarren/full-moon/blob/633774a2d8d9b0fee7156f5db544dc246f70d60c/full-moon/src/ast/parser_util.rs#L299-L304

since `if let Ok(...) = ... {` fails, it follows the else branch, which **returns a successful parsing of an _empty_ `ZeroOrMoreDelimited`**. (If we look at `keep_going!`, it only exits completely if we get an error other than NoMatch)

Since ZeroOrMoreDelimited is succesfully parsed, but no tokens were consumed, the parser is in an incorrect state.

The only way to solve this *really* is to prevent `ParseTypeFieldKey` from returning a `NoMatch` error, but this leads to other problems. Tbh this is mainly a problem of the parser being greedy and backtracking. This would better be solved if parsing was changed similar to the prototype that was mentioned on discord by lpg. I imagine @Kampfkarren wants to take that on though, since thats a major refactor of parsing.
