### ISSUE TITLE
Luau string interpolation

### ISSUE THREAD

**Issue by Kampfkarren** [Kampfkarren/full-moon#235]
https://github.com/Roblox/luau/pull/614

**Comment by sno2** [comment]
Hello, should such a feature be hidden under a Cargo feature (e.g. `"rfc-string-interpolation"`) or can this be added on main?

**Comment by Kampfkarren** [comment]
It should just be added under the roblox feature flag, which is the misnomer feature flag for Luau.

**Comment by sno2** [comment]
Ok, thanks. I am going to try to implement this.

**Comment by Kampfkarren** [comment]
Good luck! You can feel free to reference the code I wrote for it in Luau (written in C++).

Make sure to include the test cases I gave to them as well, both for passing and failure.

**Comment by sno2** [comment]
> Good luck! You can feel free to reference the code I wrote for it in Luau (written in C++).

Thanks, I'll make sure to check it for the structures.

> Make sure to include the test cases I gave to them as well, both for passing and failure.

👍

**Comment by sno2** [comment]
Hello, I am back again. Anyways, I have some solemn news. Basically, I came up with an implementation that works well, but it utilizes logos extras to attach abstract data to the tokenizer.

https://docs.rs/logos/latest/logos/trait.Logos.html#associatedtype.Extras

The problem is, we need to store a count of the open braces within template interpolations at a given moment. But, we also need to store that count for every template literal and the template literals nested within that template literal.  Therefore, we need some sort of `Vec<usize>` to hold the counts for each level.  However, `Tokenizer` implements `Copy`, and `Vec<usize>` does not.  So, it's impossible to get some sort of dynamic allocation in the extras without unsafe code which would definitely be unsound.

You could also use a `[usize; 8]` and just assume the user would not nest more than 8 template literals, but that would also expose users using this library to an extremely easy security vulnerability.  Not sure the route to take from here.

**Comment by Kampfkarren** [comment]
Will investigate further, CC @Rerumu if they have any ideas

**Comment by sno2** [comment]
> Will investigate further, CC @Rerumu if they have any ideas

Ok, thanks. I've created a draft PR with what I attempted in #235

**Comment by Kampfkarren** [comment]
Do you mean `Atom` isn't Copy anymore? Does it need to be?

**Comment by sno2** [comment]
No, see the FIXME in the draft PR. We need to dynamically grow a vector in the extras struct somehow but we can't because it needs `Copy`.

**Comment by Rerumu** [comment]
It should be possible to implement interpolation without extras or messing with containers I think. Depending on how we want to lex it there are multiple approaches.

There is the lazy approach of lexing backticks as a normal string from end to end. The handler function can deal with the nesting by setting up a stack and whatnot without having to store it in the lexer itself. After this, a secondary lexer can be used at a later stage to extract the inner tokens from the string.

If we want an eager approach instead, we can make a single backtick pattern and have whatever code is handling it switch over to an appropriate secondary lexer upon encountering that "signal".
